trigger:
   - master

variables:
   imageName: 'springbootapp'
   acrName: 'employee'
   acrLoginServer: 'employee.azurecr.io'

pool:
   vmImage: 'ubuntu-latest'

steps:

- task: Maven@3
  inputs:
     mavenPomFile: 'employeemanagement/pom.xml'
     goals: 'package'
     options: '-DskipTests'
displayName: 'Maven Build - Package JAR'      

- task: Docker@2
  inputs: 
     containerRegiistry: 'ACRServiceConnection'
     repository: '$(imageName)'
     command: 'buildAndPush'
     Dockerfile: 'employeemanagement/Dockerfile'
     tags: |
        latest
displayName: 'Docker Build and Push to ACR'


- script: echo "Image build and push completes successfully!"
  displayName: 'Success Message'
